// ── FROZEN CONTRACT ─────────────────────────────────────────────────────────
// The seam between the AGENT lane (Person A) and the DATA lane (Person B).
// Source of truth. Both /agent and /ui mirror these. Do NOT change without
// telling the other lane. See data/PLAN.md §4 for the full spec.
// Frozen constants: N=3 approvals → auto · load>70 = overloaded · decision() upserts by id.

export type Source = "github" | "slack" | "email";
export type WorkStatus = "open" | "in_progress" | "stale" | "done";
export type WorkType = "task" | "email" | "review";

export interface WorkItem {
  id: string;                       // source-prefixed, e.g. "gh-412", "slack-88", "email-7"
  source: Source;
  title: string;
  owner_suggested: string | null;   // an assignee id (person OR agent); null = unassigned
  age_days: number;
  status: WorkStatus;
  is_duplicate_of: string | null;   // another work_item.id; null = not a dup
  type: WorkType;
}

export type AssigneeKind = "person" | "agent";

export interface Workload {
  assignee: string;                 // lowercase slug, e.g. "sasha", "triage-bot"
  kind: AssigneeKind;               // person OR agent
  open_tasks: number;
  est_load_score: number;           // 0–100; > 70 = overloaded (FROZEN)
}

export type Stakes = "low" | "high";
export type ManagerResponse =
  | "approved" | "overridden" | "edited" | "pending" | "n/a";

// What the agent SENDS to POST /decision (it classifies category/stakes/reversible).
export interface DecisionInput {
  id: string;                       // uuid generated by agent (so re-call = upsert)
  item_id: string | null;
  category: string;                 // "issue-triage" | "capacity-assignment" | "candidate-decision" | ...
  action: string;                   // human-readable, e.g. "closed gh-412 as dup of gh-389"
  stakes: Stakes;
  reversible: boolean;
  was_autonomous: boolean;          // true = acted alone; false = escalated
  manager_response: ManagerResponse;// "n/a" if autonomous, "pending" when first escalated
}

// What the data lane STORES / returns (adds id confirmation + timestamp).
export interface Decision extends DecisionInput {
  timestamp: string;                // ISO 8601, set by data lane on write
}

export type TrustLevel = "ask" | "auto";

export interface Trust {
  category: string;                 // matches Decision.category
  trust_level: TrustLevel;          // what the agent's act-vs-escalate branch reads
  approvals_count: number;
  overrides_count: number;
  ceiling: boolean;                 // true = ALWAYS escalates; trust can never promote it
}

// GET /context response
export interface ContextSnapshot {
  work_items: WorkItem[];
  workload: Workload[];
  trust: Trust[];
}

// POST /decision response
export interface DecisionResult {
  decision: Decision;
  trust: Trust;                     // the UPDATED trust row for decision.category
}
