// ── FROZEN CONTRACT ─────────────────────────────────────────────────────────
// The seam between the AGENT lane (Person A) and the DATA lane (Person B).
// Source of truth. Both /agent and /ui mirror these. Do NOT change without
// telling the other lane. See data/PLAN.md §4 for the full spec.
// Frozen constants: N=3 approvals → auto · load>70 = overloaded · decision() upserts by id.

export type Source = "github" | "slack" | "email";
export type WorkStatus = "open" | "in_progress" | "stale" | "done";
export type WorkType = "task" | "email" | "review";

export interface WorkItem {
  id: string;                       // source-prefixed, e.g. "gh-412", "slack-88", "email-7"
  source: Source;
  title: string;
  owner_suggested: string | null;   // an assignee id (person OR agent); null = unassigned
  age_days: number;
  status: WorkStatus;
  is_duplicate_of: string | null;   // another work_item.id; null = not a dup
  type: WorkType;
}

export type AssigneeKind = "person" | "agent";

export interface Workload {
  assignee: string;                 // lowercase slug, e.g. "sasha", "triage-bot"
  kind: AssigneeKind;               // person OR agent
  open_tasks: number;
  est_load_score: number;           // 0–100; > 70 = overloaded (FROZEN)
}

export type Stakes = "low" | "high";
export type ManagerResponse =
  | "approved" | "overridden" | "edited" | "pending" | "n/a";

// What the agent SENDS to POST /decision (it classifies category/stakes/reversible).
export interface DecisionInput {
  id: string;                       // uuid generated by agent (so re-call = upsert)
  item_id: string | null;
  category: string;                 // "issue-triage" | "capacity-assignment" | "candidate-decision" | ...
  action: string;                   // human-readable, e.g. "closed gh-412 as dup of gh-389"
  stakes: Stakes;
  reversible: boolean;
  was_autonomous: boolean;          // true = acted alone; false = escalated
  manager_response: ManagerResponse;// "n/a" if autonomous, "pending" when first escalated
}

// What the data lane STORES / returns (adds id confirmation + timestamp).
export interface Decision extends DecisionInput {
  timestamp: string;                // ISO 8601, set by data lane on write
}

// MERGED CONTRACT (agent lane × data lane). The agent-lane router reads
// `autonomy_level`; Person B's Bayesian engine produces `trust_score` and the
// extras. autonomy_level is DERIVED from trust_score (see MISMATCHES.md item 1 —
// the derivation should live in trust.py).
// Tiers: 0 observer (read-only) · 1 reversible (comment/label/nudge) · 2 routine (assign/close/send).
export type AutonomyLevel = 0 | 1 | 2;
export type TrustLevel = "ask" | "auto";   // legacy/derived: autonomy_level >= 2 ? "auto" : "ask"
export type RiskProfile = "low" | "medium" | "high";

export interface Trust {
  category: string;                 // matches Decision.category
  // ── routing signal (agent lane reads this) ──
  autonomy_level: AutonomyLevel;    // the tier this category has EARNED (router maps level → agent)
  ceiling: boolean;                 // true = capped at level 0, forever
  // ── Bayesian engine (data lane) ──
  trust_score: number;              // 0..1 Bayesian posterior (Beta MAP, time-decayed)
  trust_confidence: number;         // 0..1 certainty (saturates with sample size)
  approvals_count: number;
  overrides_count: number;
  // ── optional engine extras (power the trust dashboard) ──
  auto_threshold?: number;          // score needed to promote (risk-adjusted)
  decay_half_life?: number;         // days
  risk_profile?: RiskProfile;       // inferred from category; drives auto_threshold
  last_event?: string;              // plain-English last trust change
  trust_level?: TrustLevel;         // legacy binary convenience
}

// GET /context response
export interface ContextSnapshot {
  work_items: WorkItem[];
  workload: Workload[];
  trust: Trust[];
}

// POST /decision response
export interface DecisionResult {
  decision: Decision;
  trust: Trust;                     // the UPDATED trust row for decision.category
}
